package com.github.creme332.model;

public enum Mode {
    MOVE_CANVAS("MOVE_CANVAS"),
    DRAW_FREEHAND("DRAW_FREEHAND"),

    DRAW_LINE_DDA("DRAW_LINE_DDA"),
    DRAW_LINE_BRESENHAM("DRAW_LINE_BRESENHAM"),

    DRAW_CIRCLE_DYNAMIC("DRAW_CIRCLE_DYNAMIC"),
    DRAW_CIRCLE_FIXED("DRAW_CIRCLE_FIXED"),

    DRAW_ELLIPSE("DRAW_ELLIPSE"),

    DRAW_POLYGON_DYNAMIC("DRAW_POLYGON_DYNAMIC"),
    DRAW_REGULAR_POLYGON("DRAW_REGULAR_POLYGON"),

    REFLECT_ABOUT_LINE("REFLECT_ABOUT_LINE"),
    REFLECT_ABOUT_POINT("REFLECT_ABOUT_POINT"),

    ROTATE_AROUND_POINT(""),

    ZOOM_IN("ZOOM_IN"),
    ZOOM_OUT("ZOOM_OUT"),
    DELETE("DELETE"),
    MOVE_GRAPHICS_VIEW("MOVE_GRAPHICS_VIEW");

    private final String mode;

    Mode(String mode) {
        this.mode = mode;
    }
}
